# Generated by Django 2.2.5 on 2020-12-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20201228_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.ActivityGroup'),
        ),
    ]
