# Generated by Django 2.2.5 on 2020-12-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20201228_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.TextField(default='Belgium', null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='postcode',
            field=models.TextField(default='', null=True),
        ),
    ]
