# Generated by Django 2.2.5 on 2020-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20201228_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='city',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(default='Belgium', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='postcode',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
