# Generated by Django 2.2.5 on 2020-12-28 15:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20201228_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='activity',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
