# Generated by Django 2.2.5 on 2020-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20201228_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='activity',
        ),
        migrations.AddField(
            model_name='entity',
            name='activity',
            field=models.ManyToManyField(to='entities.Activity'),
        ),
    ]
